// Code generated by MockGen. DO NOT EDIT.
// Source: ./warehouse.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/douglmendes/mercado-fresco-round-go/internal/warehouses/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWarehouseService is a mock of WarehouseService interface.
type MockWarehouseService struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseServiceMockRecorder
}

// MockWarehouseServiceMockRecorder is the mock recorder for MockWarehouseService.
type MockWarehouseServiceMockRecorder struct {
	mock *MockWarehouseService
}

// NewMockWarehouseService creates a new mock instance.
func NewMockWarehouseService(ctrl *gomock.Controller) *MockWarehouseService {
	mock := &MockWarehouseService{ctrl: ctrl}
	mock.recorder = &MockWarehouseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseService) EXPECT() *MockWarehouseServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWarehouseService) Create(address, telephone, warehouseCode string) (*domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", address, telephone, warehouseCode)
	ret0, _ := ret[0].(*domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWarehouseServiceMockRecorder) Create(address, telephone, warehouseCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWarehouseService)(nil).Create), address, telephone, warehouseCode)
}

// Delete mocks base method.
func (m *MockWarehouseService) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWarehouseServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWarehouseService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockWarehouseService) GetAll() ([]domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWarehouseServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWarehouseService)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockWarehouseService) GetById(id int) (domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockWarehouseServiceMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockWarehouseService)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockWarehouseService) Update(id int, address, telephone, warehouseCode string) (domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, address, telephone, warehouseCode)
	ret0, _ := ret[0].(domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWarehouseServiceMockRecorder) Update(id, address, telephone, warehouseCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWarehouseService)(nil).Update), id, address, telephone, warehouseCode)
}

// MockWarehouseRepository is a mock of WarehouseRepository interface.
type MockWarehouseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseRepositoryMockRecorder
}

// MockWarehouseRepositoryMockRecorder is the mock recorder for MockWarehouseRepository.
type MockWarehouseRepositoryMockRecorder struct {
	mock *MockWarehouseRepository
}

// NewMockWarehouseRepository creates a new mock instance.
func NewMockWarehouseRepository(ctrl *gomock.Controller) *MockWarehouseRepository {
	mock := &MockWarehouseRepository{ctrl: ctrl}
	mock.recorder = &MockWarehouseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseRepository) EXPECT() *MockWarehouseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWarehouseRepository) Create(id int, address, telephone, warehouseCode string) (domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", id, address, telephone, warehouseCode)
	ret0, _ := ret[0].(domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWarehouseRepositoryMockRecorder) Create(id, address, telephone, warehouseCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWarehouseRepository)(nil).Create), id, address, telephone, warehouseCode)
}

// Delete mocks base method.
func (m *MockWarehouseRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWarehouseRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWarehouseRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockWarehouseRepository) GetAll() ([]domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWarehouseRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWarehouseRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockWarehouseRepository) GetById(id int) (domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockWarehouseRepositoryMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockWarehouseRepository)(nil).GetById), id)
}

// LastID mocks base method.
func (m *MockWarehouseRepository) LastID() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockWarehouseRepositoryMockRecorder) LastID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockWarehouseRepository)(nil).LastID))
}

// Update mocks base method.
func (m *MockWarehouseRepository) Update(id int, address, telephone, warehouseCode string) (domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, address, telephone, warehouseCode)
	ret0, _ := ret[0].(domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWarehouseRepositoryMockRecorder) Update(id, address, telephone, warehouseCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWarehouseRepository)(nil).Update), id, address, telephone, warehouseCode)
}
