definitions:
  controllers.request:
    properties:
      address:
        type: string
      cid:
        type: integer
      company_name:
        type: string
      telephone:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/sellers:
    get:
      description: get sellers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.request'
        "404":
          description: Not Found
          schema:
            type: string
      summary: List sellers
      tags:
      - Sellers
    post:
      consumes:
      - application/json
      description: create sellers
      parameters:
      - description: Seller to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/controllers.request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Create sellers
      tags:
      - Sellers
  /api/v1/sellers/{id}:
    delete:
      description: delete seller
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/controllers.request'
      summary: Delete seller
      tags:
      - Sellers
    get:
      consumes:
      - application/json
      description: get seller
      parameters:
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.request'
        "404":
          description: Not Found
          schema:
            type: string
      summary: List seller
      tags:
      - Sellers
    patch:
      consumes:
      - application/json
      description: update seller
      parameters:
      - description: Seller to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/controllers.request'
      - description: Seller ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.request'
      summary: Update seller
      tags:
      - Sellers
swagger: "2.0"
